name: Petstore API tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ vars.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Build and test
      uses: docker/build-push-action@v6
      with:
        target: production
        load: true
    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        push: true
        tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: npm install and test
      id: execute
      run: |
        npm ci
        npm test
        echo "test-results-path=$GITHUB_WORKSPACE/mochawesome-report" >> $GITHUB_OUTPUT
    - name: Archive mochawesome test results
      uses: actions/upload-artifact@v4
      with:
        name: mochawesome-report
        include-hidden-files: true
        path: |
          ${{steps.execute.outputs.test-results-path}}/*
          !**/*.zip
