# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: npm install and test
      id: execute
      run: |
        npm install
        npm test
        echo "test-results-path=$GITHUB_WORKSPACE/mochawesome-report" >> $GITHUB_OUTPUT
    - name: Archive mochawesome test results
      uses: actions/upload-artifact@v4
      with:
        name: mochawesome-report
        include-hidden-files: true
        path: |
          ${{steps.execute.outputs.test-results-path}}/*
          !**/*.zip
