name: Petstore API tests

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t petstore-api-test-image .

    - name: Run API tests in Docker
      id: execute
      run: |
        docker run --rm petstore-api-test-image npm run test
        echo "test-results-path=$GITHUB_WORKSPACE/mochawesome-report" >> $GITHUB_OUTPUT
    - name: Archive mochawesome test results
      uses: actions/upload-artifact@v4
      with:
        name: mochawesome-report
        include-hidden-files: true
        path: |
          /app/mochawesome-report/*
          !**/*.zip