name: Petstore API tests

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [24.x]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t petstore-api-test-image .

    - name: Run API tests in Docker
      run: docker run --rm petstore-api-test-image npm run test

    - name: Upload Test Report
      uses: actions/upload-artifact@v4
      with:
        name: mocha-test-report
        path: |
          ./app/mochawesome-report/*
          !**/*.zip